version: '2'

services:
  app:
    build: .
    volumes:
      - ~/.aws:/root/.aws
      - api_node_modules:/app/api/node_modules
      - web_node_modules:/app/web/node_modules
      - .:/app
    ports:
      - 3001:3000

volumes:
  api_node_modules:
  web_node_modules: