version: '2'

services:
  api:
    build: ./api
    volumes:
      - ~/.aws:/root/.aws
      - api_node_modules:/api/node_modules
      - ./api:/api
    ports:
      - 5000:5000
    environment:
      - ENV:${ENV}

  web:
    build: ./web
    volumes:
      - ~/.aws:/root/.aws
      - web_node_modules:/web/node_modules
      - ./web:/web
    links:
      - api
    ports:
      - 3000:3000
    env_file:
      - ${ENV}.env
    environment:
      - PORT=3000
      - ${ENV}.env

volumes:
  api_node_modules:
  web_node_modules: