# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: serverless-okta

custom:
  webpack:
    packager: 'yarn'

plugins:
  - serverless-offline
  - serverless-webpack

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2
  stage: ${opt:stage, 'local'}

# The `functions` block defines what code to deploy
functions:

  authorize:
    handler: functions/oktaAuthorize.handler
    environment:
      ISSUER: ${file(./config.${self:provider.stage}.json):issuer}
      AUDIENCE: ${file(./config.${self:provider.stage}.json):audience}
      CID: ${file(./config.${self:provider.stage}.json):client_id}
      JWKS: ${ssm:/okta/develop/jwks}

  getCats:
    handler: functions/getCats.handler
    events:
      - http:
          path: api/cats
          method: get
          cors: true
          # authorizer: authorize # Cats are public

  getPangolins:
    handler: functions/getPangolins.handler
    events:
      - http:
          path: api/pangolins
          method: get
          cors: true
          authorizer:
            name: authorize
            resultTtlInSeconds: 300
            identitySource: method.request.header.Authorization
            identityValidationExpression: ^Bearer [-0-9a-zA-z\.]*$
            type: token